import { Image } from 'expo-image';
import { ReactNode } from 'react';
import { StyleProp, StyleSheet, View, ViewStyle } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { colors } from '@/theme';

// The chalkboard texture (a dark board smudged with freshly-erased chalk),
// generated by ai-tooling/generate-chalkboard.js.
const CHALKBOARD = require('../../assets/images/chalkboard.png');

interface ScreenProps {
  children: ReactNode;
  /** Container styles (horizontal padding, top padding, etc.). Don't set a
   *  bottom padding here — `bottomOffset` owns the bottom so it can't be lost. */
  style?: StyleProp<ViewStyle>;
  /** Extra padding below the safe-area inset, e.g. breathing room above the
   *  nav bar. The bottom padding is always at least the inset. */
  bottomOffset?: number;
  /** Draw the chalkboard background. Default true. */
  board?: boolean;
}

/**
 * Full-height screen container that always reserves room for the Android system
 * navigation bar / gesture area at the bottom. Pin buttons or other controls to
 * the bottom of a `<Screen>` and they can never be drawn under the nav bar again
 * — the safe-area bottom inset is applied here, once, instead of being remembered
 * per screen.
 *
 * It also paints the chalkboard backdrop: a photographed-looking board smudged
 * with freshly-erased chalk, behind the content. The image never intercepts taps
 * (it sits below the content, which is drawn after it); opaque cards/inputs
 * layered on top read as paper and supplies on the board. Lists/wrappers should
 * stay transparent so the board shows through, and text drawn straight on it
 * uses `colors.chalk`.
 *
 * The inset is layered after `style` so a screen's own container styles can't
 * accidentally cancel it. The top is intentionally left to the navigation
 * header, which already clears the status bar.
 */
export function Screen({ children, style, bottomOffset = 0, board = true }: ScreenProps) {
  const insets = useSafeAreaInsets();
  return (
    <View style={styles.root}>
      {board ? (
        <Image source={CHALKBOARD} style={StyleSheet.absoluteFill} contentFit="cover" />
      ) : null}
      <View style={[styles.flex, style, { paddingBottom: insets.bottom + bottomOffset }]}>
        {children}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  // The board color is the fallback while the image loads and the tone behind
  // the navigation header, so the header reads as part of the same board.
  root: { flex: 1, backgroundColor: colors.chalkboard },
  flex: { flex: 1 },
});
